import type { InstitutionGroup } from "@/types/financial-institution"

export const institutionGroups: InstitutionGroup[] = [
  {
    id: "big-6",
    title: "Major National Banks",
    institutions: [
      { id: "chase", name: "Chase", category: "big-6" },
      { id: "bank-of-america", name: "Bank of America", category: "big-6" },
      { id: "wells-fargo", name: "Wells Fargo", category: "big-6" },
      { id: "citibank", name: "Citibank", category: "big-6" },
      { id: "us-bank", name: "U.S. Bank", category: "big-6" },
      { id: "pnc", name: "PNC Bank", category: "big-6" },
      { id: "truist", name: "Truist", category: "big-6" },
      { id: "capital-one", name: "Capital One", category: "big-6" },
    ],
  },
  {
    id: "online-only",
    title: "Online-Only Banks & Neobanks",
    institutions: [
      { id: "ally", name: "Ally Bank", category: "online-only" },
      { id: "chime", name: "Chime", category: "online-only" },
      { id: "sofi", name: "SoFi", category: "online-only" },
      { id: "marcus", name: "Marcus by Goldman Sachs", category: "online-only" },
      { id: "discover", name: "Discover Bank", category: "online-only" },
      { id: "american-express", name: "American Express Banking", category: "online-only" },
      { id: "varo", name: "Varo Bank", category: "online-only" },
      { id: "current", name: "Current", category: "online-only" },
      { id: "aspiration", name: "Aspiration", category: "online-only" },
    ],
  },
  {
    id: "schedule-i-ii",
    title: "Regional & Community Banks",
    institutions: [
      { id: "regions", name: "Regions Bank", category: "schedule-i-ii" },
      { id: "fifth-third", name: "Fifth Third Bank", category: "schedule-i-ii" },
      { id: "key-bank", name: "KeyBank", category: "schedule-i-ii" },
      { id: "huntington", name: "Huntington Bank", category: "schedule-i-ii" },
      { id: "m-and-t", name: "M&T Bank", category: "schedule-i-ii" },
      { id: "citizens", name: "Citizens Bank", category: "schedule-i-ii" },
      { id: "td-bank", name: "TD Bank", category: "schedule-i-ii" },
      { id: "bmo-harris", name: "BMO Harris", category: "schedule-i-ii" },
      { id: "santander", name: "Santander Bank", category: "schedule-i-ii" },
      { id: "first-horizon", name: "First Horizon", category: "schedule-i-ii" },
      { id: "synovus", name: "Synovus", category: "schedule-i-ii" },
      { id: "comerica", name: "Comerica", category: "schedule-i-ii" },
    ],
  },
  {
    id: "credit-unions",
    title: "Credit Unions",
    institutions: [
      { id: "navy-federal", name: "Navy Federal Credit Union", category: "credit-unions" },
      { id: "state-employees", name: "State Employees' Credit Union", category: "credit-unions" },
      { id: "pentagon-federal", name: "Pentagon Federal Credit Union", category: "credit-unions" },
      { id: "schools-first", name: "SchoolsFirst FCU", category: "credit-unions" },
      { id: "golden-1", name: "Golden 1 Credit Union", category: "credit-unions" },
      { id: "america-first", name: "America First Credit Union", category: "credit-unions" },
      { id: "alliant", name: "Alliant Credit Union", category: "credit-unions" },
      { id: "service", name: "Service Credit Union", category: "credit-unions" },
      { id: "bethpage", name: "Bethpage Federal Credit Union", category: "credit-unions" },
      { id: "randolph-brooks", name: "Randolph-Brooks FCU", category: "credit-unions" },
      { id: "mountain-america", name: "Mountain America Credit Union", category: "credit-unions" },
      { id: "nasa", name: "NASA Federal Credit Union", category: "credit-unions" },
      { id: "suncoast", name: "Suncoast Credit Union", category: "credit-unions" },
      { id: "redstone", name: "Redstone Federal Credit Union", category: "credit-unions" },
      { id: "security-service", name: "Security Service FCU", category: "credit-unions" },
    ],
  },
  {
    id: "digital-hybrid",
    title: "Digital & Hybrid Banks",
    institutions: [
      { id: "simple", name: "Simple", category: "digital-hybrid" },
      { id: "one-finance", name: "One Finance", category: "digital-hybrid" },
      { id: "axos", name: "Axos Bank", category: "digital-hybrid" },
      { id: "cit", name: "CIT Bank", category: "digital-hybrid" },
      { id: "synchrony", name: "Synchrony Bank", category: "digital-hybrid" },
      { id: "webbank", name: "WebBank", category: "digital-hybrid" },
      { id: "first-internet", name: "First Internet Bank", category: "digital-hybrid" },
      { id: "quontic", name: "Quontic Bank", category: "digital-hybrid" },
    ],
  },
]
