import type { RemittanceClass } from "@/types/remittance"

/**
 * Default catalog of remittance classes covering common transfer scenarios
 */
export const REMITTANCE_CLASSES: RemittanceClass[] = [
  // Domestic Personal Instant Wire
  {
    id: "domestic_personal_instant_wire_outbound",
    label: "Domestic • Personal • Instant Wire (Outbound)",
    scope: "domestic",
    entityType: "personal",
    speed: "instant",
    method: "wire",
    direction: "outbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Fast personal wire transfers within Canada for immediate settlement",
  },
  {
    id: "domestic_personal_instant_wire_inbound",
    label: "Domestic • Personal • Instant Wire (Inbound)",
    scope: "domestic",
    entityType: "personal",
    speed: "instant",
    method: "wire",
    direction: "inbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Receive instant wire transfers from other Canadian banks",
  },

  // Domestic Commercial Batch ACH/EFT
  {
    id: "domestic_commercial_batch_ach_outbound",
    label: "Domestic • Commercial • Batch ACH/EFT (Outbound)",
    scope: "domestic",
    entityType: "commercial",
    speed: "batch",
    method: "ach_eft",
    direction: "outbound",
    valueTier: "retail",
    purpose: "vendor",
    description: "Bulk vendor payments and accounts payable via ACH/EFT",
  },
  {
    id: "domestic_commercial_batch_ach_inbound",
    label: "Domestic • Commercial • Batch ACH/EFT (Inbound)",
    scope: "domestic",
    entityType: "commercial",
    speed: "batch",
    method: "ach_eft",
    direction: "inbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Receive bulk commercial payments via ACH/EFT",
  },

  // International Personal Instant Mobile/Wallet
  {
    id: "international_personal_instant_wallet_outbound",
    label: "International • Personal • Instant Mobile/Wallet (Outbound)",
    scope: "international",
    entityType: "personal",
    speed: "instant",
    method: "mobile_wallet",
    direction: "outbound",
    valueTier: "micro",
    purpose: "settlement",
    description: "Small cross-border transfers via mobile wallet apps",
  },
  {
    id: "international_personal_instant_wallet_inbound",
    label: "International • Personal • Instant Mobile/Wallet (Inbound)",
    scope: "international",
    entityType: "personal",
    speed: "instant",
    method: "mobile_wallet",
    direction: "inbound",
    valueTier: "micro",
    purpose: "settlement",
    description: "Receive micro-remittances from abroad via mobile wallet",
  },

  // International Commercial Same-day Wire
  {
    id: "international_commercial_sameday_wire_outbound",
    label: "International • Commercial • Same-day Wire (Outbound)",
    scope: "international",
    entityType: "commercial",
    speed: "same_day",
    method: "wire",
    direction: "outbound",
    valueTier: "high_value",
    purpose: "settlement",
    description: "High-value cross-border wire transfers for business",
  },
  {
    id: "international_commercial_sameday_wire_inbound",
    label: "International • Commercial • Same-day Wire (Inbound)",
    scope: "international",
    entityType: "commercial",
    speed: "same_day",
    method: "wire",
    direction: "inbound",
    valueTier: "high_value",
    purpose: "settlement",
    description: "Receive high-value international wire transfers",
  },

  // Domestic Payroll Batch ACH/EFT
  {
    id: "domestic_commercial_batch_ach_payroll_outbound",
    label: "Domestic • Payroll • Batch ACH/EFT (Outbound)",
    scope: "domestic",
    entityType: "commercial",
    speed: "batch",
    method: "ach_eft",
    direction: "outbound",
    valueTier: "retail",
    purpose: "payroll",
    description: "Bulk payroll processing via direct deposit",
  },

  // Domestic Government Same-day ACH/EFT
  {
    id: "domestic_government_sameday_ach_outbound",
    label: "Domestic • Government • Same-day ACH/EFT (Outbound)",
    scope: "domestic",
    entityType: "government",
    speed: "same_day",
    method: "ach_eft",
    direction: "outbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Government disbursements like tax refunds and benefits",
  },
  {
    id: "domestic_government_sameday_ach_inbound",
    label: "Domestic • Government • Same-day ACH/EFT (Inbound)",
    scope: "domestic",
    entityType: "government",
    speed: "same_day",
    method: "ach_eft",
    direction: "inbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Receive tax payments and government fees",
  },

  // Domestic Escrow Deferred Wire
  {
    id: "domestic_institutional_deferred_wire_outbound",
    label: "Domestic • Escrow • Deferred Wire (Outbound)",
    scope: "domestic",
    entityType: "institutional",
    speed: "deferred",
    method: "wire",
    direction: "outbound",
    valueTier: "high_value",
    purpose: "escrow",
    description: "Scheduled escrow releases for real estate transactions",
  },
  {
    id: "domestic_institutional_deferred_wire_inbound",
    label: "Domestic • Escrow • Deferred Wire (Inbound)",
    scope: "domestic",
    entityType: "institutional",
    speed: "deferred",
    method: "wire",
    direction: "inbound",
    valueTier: "high_value",
    purpose: "escrow",
    description: "Receive funds into escrow for future settlement",
  },

  // Domestic Refund Batch ACH/EFT
  {
    id: "domestic_commercial_batch_ach_refund_outbound",
    label: "Domestic • Refund • Batch ACH/EFT (Outbound)",
    scope: "domestic",
    entityType: "commercial",
    speed: "batch",
    method: "ach_eft",
    direction: "outbound",
    valueTier: "retail",
    purpose: "refund",
    description: "Bulk customer refunds and credit settlements",
  },

  // Additional coverage for card rails
  {
    id: "domestic_personal_instant_card_outbound",
    label: "Domestic • Personal • Instant Card Rail (Outbound)",
    scope: "domestic",
    entityType: "personal",
    speed: "instant",
    method: "card_rail",
    direction: "outbound",
    valueTier: "micro",
    purpose: "settlement",
    description: "Card-based instant transfers like Zelle",
  },
  {
    id: "international_personal_instant_card_outbound",
    label: "International • Personal • Instant Card Rail (Outbound)",
    scope: "international",
    entityType: "personal",
    speed: "instant",
    method: "card_rail",
    direction: "outbound",
    valueTier: "retail",
    purpose: "settlement",
    description: "Cross-border card network transfers",
  },
]
